/* View functions are presentation-only; data stays tied to its source snapshot. */
(function(){
'use strict';const E=BA.escape,U=BAUI;
function current(m){return m.state.documents.find(d=>d.id===m.selectedDoc)||m.state.documents.find(d=>d.id===m.state.current_id);}
function allRows(m){return m.state.documents.filter(d=>['approved','superseded'].includes(d.status)).flatMap(d=>d.rows);}
function displayed(m){let rows=m.onlySaved?BA.savedGroups(m.state.documents,m.prefs.favorites,m.filters).flatMap(g=>g.rows):BA.filter(current(m)?.rows||[],m.filters);if(m.onlyProfile)rows=rows.filter(r=>m.prefs.functions.includes(r.function_code));return rows;}
function canCheck(m){return m.state.mode==='server'&&m.state.capabilities?.source_check==='available';}
function refreshButton(m){return U.button('sync',canCheck(m)?'Comprobar ahora':'Buscar copia actualizada','refresh','primary',m.refreshing?'disabled':'');}
function freshness(m){const f=m.state.freshness||{},time={hour:'2-digit',minute:'2-digit'};return `<p>Último intento: ${E(BA.date(f.last_attempt_at,time))}. Última comprobación completa: ${E(BA.date(f.last_success_at,time))}. Estado: ${E({completed:'completada',partial:'parcial',failed:'fallida',running:'en curso',never:'sin comprobación'}[f.status]||'sin comprobación registrada')}.</p>`;}
function historyNotice(m){const h=m.state.history_window;if(!(Number(h?.omitted_documents)>0))return '';return U.notice('Historial publicado limitado',`${E(h.note||'Esta copia pública solo incluye las publicaciones recientes.')} Se omiten ${E(h.omitted_documents)} documentos. Los favoritos de copias no incluidas siguen guardados en este navegador, pero sus filas no están disponibles en esta consulta.`, 'neutral');}
function coverage(m){const doc=current(m),pending=(m.state.catalog.notices||[]).filter(n=>BA.isPendingNotice(n,m.state.documents,m.state.history_documents));
 const title=doc?`Copia incorporada: ${E(BA.date(doc.published_at))}`:'Todavía no hay una copia incorporada.';
 return U.notice(title,`La consulta refleja una publicación, no la disponibilidad actual. ${pending.length?E(pending.length)+' publicación(es) sin incorporar. ':''}${canCheck(m)?'La comprobación cubre los anuncios y PDF de vacantes sin cubrir de Secundaria y otros cuerpos.':'Se muestra una copia publicada. Buscar otra copia no comprueba las fuentes oficiales.'}${freshness(m)}`,pending.length||m.state.freshness?.status==='partial'?'warning':'neutral')+(m.refreshing?`<div class="notice neutral" role="status"><span id="refresh-status">${E(m.refreshMessage||'Buscando publicaciones…')}</span></div>`:'');
}
function header(title,description,actions=''){return `<div class="page-header"><div><h1>${E(title)}</h1><p>${E(description)}</p></div>${actions?`<div class="buttons">${actions}</div>`:''}</div>`;}
function vacancies(m){const doc=current(m),rows=m.onlySaved?allRows(m):doc?.rows||[],approved=m.state.documents.filter(d=>d.status==='approved');
 return header('Vacantes sin cubrir','Explora las copias incorporadas. Filtra lo que te interesa y comprueba cada dato en su origen.',refreshButton(m)+U.button('export-csv','Exportar CSV','download'))+coverage(m)+
 (m.onlySaved?'':`<div class="stats"><div class="stat"><div class="stat-number">${BA.places(rows)}</div><div class="stat-label">plazas en esta copia</div></div><div class="stat"><div class="stat-number">${rows.length}</div><div class="stat-label">registros originales</div></div><div class="stat"><div class="stat-number">${BA.unique(rows,'function_code').length}</div><div class="stat-label">funciones</div></div><div class="stat"><div class="stat-number">${BA.unique(rows,'municipality').length}</div><div class="stat-label">municipios</div></div></div>`)+`
 <section class="filters" aria-label="Filtros de vacantes"><div class="search-row"><div class="search-input">${U.icon('search')}<input class="input" id="search" type="search" value="${E(m.filters.q||'')}" placeholder="Busca por función, centro, municipio o código…" aria-label="Buscar vacantes"></div><select class="copy-select" id="copy-select" ${m.onlySaved?'disabled':''} aria-label="Copia consultada">${approved.map(d=>`<option value="${E(d.id)}" ${doc?.id===d.id?'selected':''}>${E(BA.date(d.published_at))}</option>`).join('')}</select></div>
 <div class="filter-grid">${U.select('function_code','Función',BA.unique(rows,'function_code','function'),m.filters.function_code,'Todas las funciones')}${U.select('body_code','Cuerpo',BA.unique(rows,'body_code','body'),m.filters.body_code,'Todos los cuerpos')}${U.select('municipality','Municipio',BA.unique(rows,'municipality'),m.filters.municipality,'Todos los municipios')}${U.select('workload','Jornada',[['full','Completa'],['partial','Parcial']],m.filters.workload,'Cualquier jornada')}${U.select('language','Mención bilingüe',BA.unique(rows,'language'),m.filters.language,'Todas')}</div>
 <div class="filter-extra"><div class="checks"><label class="inline-check"><input id="only-saved" type="checkbox" ${m.onlySaved?'checked':''}>Solo guardadas <span class="muted">(${allRows(m).filter(r=>m.prefs.favorites.includes(r.id)).length})</span></label><label class="inline-check"><input id="only-profile" type="checkbox" ${m.onlyProfile?'checked':''}>Mis funciones <span class="muted">(${m.prefs.functions.length})</span></label></div>${U.button('clear-filters','Restablecer','','text')}</div>
 <details class="more-filters" ${m.filters.cupo||m.filters.itinerant?'open':''}><summary>Más filtros: cupo e itinerancia</summary><div class="extra-grid">${U.select('cupo','Cupo publicado',[['VP','VP'],['VS','VS']],m.filters.cupo,'Todos los cupos')}${U.select('itinerant','Itinerancia',[['S','Sí'],['N','No']],m.filters.itinerant,'Cualquiera')}</div></details></section>
 <div id="results">${results(m)}</div><div class="footnote">${U.icon('info')}<p>«Plazas» suma la columna <em>Sin cubrir</em>; «registros» cuenta las filas del PDF. Las filas idénticas del original se conservan. Los filtros expresan preferencias: no determinan obligaciones de participación.</p></div>`;
}
function results(m){const rows=displayed(m),size=12;m.page=Math.min(Math.max(1,m.page),Math.max(1,Math.ceil(rows.length/size)));
 if(m.onlySaved){const visible=new Set(rows.slice((m.page-1)*size,m.page*size).map(r=>r.id));const groups=BA.savedGroups(m.state.documents,m.prefs.favorites,m.filters).map(g=>({...g,rows:g.rows.filter(r=>visible.has(r.id))})).filter(g=>g.rows.length);return historyNotice(m)+`<div class="results-head"><strong>Registros guardados por copia · ${rows.length} registros</strong><span>Las cantidades pertenecen a publicaciones distintas</span></div>`+(groups.map(g=>`<section class="section"><div class="section-head"><h2>${E(BA.date(g.document.published_at))} · proceso ${E(g.document.process_id)}</h2><span>${g.rows.length} registros · ${BA.places(g.rows)} plazas en esta copia</span></div>${U.table(g.rows,m.prefs)}</section>`).join('')||U.empty('Sin registros guardados que coincidan','Los favoritos se conservan en este navegador.'))+U.pagination(m.page,rows.length,size);}
 return `<div class="results-head"><span><strong>${BA.places(rows)} plazas</strong> en <strong>${rows.length} registros</strong> ${m.filters.q||Object.values(m.filters).some(Boolean)||m.onlySaved||m.onlyProfile?'que coinciden':'en la copia seleccionada'}</span><span>Orden del documento original</span></div>`+
 (rows.length?U.table(rows.slice((m.page-1)*size,m.page*size),m.prefs):U.empty('No hay coincidencias en esta copia','Esto no significa que no existan vacantes o que no tengas que participar. Prueba otros filtros o revisa la publicación oficial.',U.button('clear-filters','Restablecer filtros')))+U.pagination(m.page,rows.length,size);
}
function changes(m){const prev=m.state.documents.find(d=>d.id===m.state.previous_id),latest=m.state.documents.find(d=>d.id===m.state.current_id),all=m.state.changes;
 const filtered=all.filter(c=>!m.changeKind||c.kind===m.changeKind);const names={appeared:'Figuran ahora',disappeared:'Ya no figuran',quantity_changed:'Cambia la cantidad'};
 const size=15;m.changePage=Math.min(Math.max(1,m.changePage),Math.max(1,Math.ceil(filtered.length/size)));
 return header('Qué ha cambiado','Diferencias observadas entre dos copias. No son adjudicaciones ni movimientos de tu lista.')+
 U.notice('Una ausencia en un listado no prueba que una plaza esté adjudicada.','La comparación agrupa filas equivalentes y suma sus cantidades. No identifica plazas individuales ni calcula posiciones personales.','neutral')+
 (prev&&latest?`<section class="panel section"><div class="act-top"><div><h2>${E(BA.date(prev.published_at))} <span class="muted">→</span> ${E(BA.date(latest.published_at))}</h2><p>Proceso ${E(prev.process_id)} → ${E(latest.process_id)} · ${E(prev.places)} → ${E(latest.places)} plazas en los listados completos.</p></div><span class="pill observed">Comparación histórica</span></div><p>${E(prev.provenance_label)} ${E(latest.provenance_label)}</p></section>
 <div class="changes-legend">${Object.entries(names).map(([k,v])=>`<span><span class="legend-count">${all.filter(c=>c.kind===k).length}</span> ${E(v.toLowerCase())}</span>`).join('')}</div>
 <div class="tabs" role="group" aria-label="Tipo de cambio"><button class="tab ${!m.changeKind?'active':''}" data-action="change-kind" aria-pressed="${!m.changeKind}" data-kind="">Todos</button>${Object.entries(names).map(([k,v])=>`<button class="tab ${m.changeKind===k?'active':''}" data-action="change-kind" aria-pressed="${m.changeKind===k}" data-kind="${k}">${v}</button>`).join('')}</div>
 <div class="data-table-wrap">${filtered.slice((m.changePage-1)*size,m.changePage*size).map(c=>`<div class="change-row"><div class="change-type">${names[c.kind]}</div><div><div class="row-primary">${E(BA.title(c.row.function))}</div><div class="row-secondary mono">${E(c.row.function_code)} · ${E(c.row.jornada)}</div></div><div><div class="row-primary">${E(BA.title(c.row.municipality))}</div><div class="row-secondary">${E(BA.title(c.row.center))}</div></div><div class="change-delta">${E(c.before)} → ${E(c.after)}</div></div>`).join('')||'<div class="empty">Sin cambios de este tipo.</div>'}</div>${U.pagination(m.changePage,filtered.length,size,'change-page')}`:
 U.empty('Se necesitan dos copias aprobadas','La comparación aparecerá al incorporar dos procesos distintos.'));
}
function acts(m){const notices=m.state.catalog.notices||[],docs=m.state.documents.filter(d=>d.status==='approved');
 return header('Actos y publicaciones','Cada copia con su fecha, alcance y documento. Sin plazos inferidos ni trámites automáticos.',U.button('mark-seen','Marcar mi revisión','check'))+
 U.notice('Las vacantes sin cubrir no son la convocatoria del acto.','Revisa convocatoria, requisitos, incidencias y resultado oficial. Tu revisión personal no acredita la comprobación de fuentes.','neutral')+
 `<div class="timeline">${notices.map(n=>`<article class="act ${BA.isPendingNotice(n,m.state.documents,m.state.history_documents)?'pending':''}"><div class="act-top"><div><h3>${E(n.title||'Publicación')} · ${E(BA.date(n.date))}</h3></div><span class="pill">${n.kind!=='vacancies'?'Aviso informativo':BA.isPendingNotice(n,m.state.documents,m.state.history_documents)?'Documento sin incorporar':'Documento incorporado'}</span></div><p>${E(n.note||n.status||'Anuncio oficial detectado')}</p><div class="buttons">${U.external(n.url,'Página oficial')}${(n.pdf_urls||[n.pdf_url]).filter(Boolean).map(url=>U.external(url,'PDF en origen')).join('')}</div></article>`).join('')}
 ${docs.map(d=>`<article class="act"><div class="act-top"><div><h3>Acto · ${E(BA.date(d.act_date))}</h3><div class="act-meta">Proceso ${E(d.process_id)} · ${E(d.act_title)}</div></div><span class="pill observed">Copia incorporada</span></div><p>Listado publicado el ${E(BA.date(d.published_at,{hour:'2-digit',minute:'2-digit'}))}. ${E(d.places)} plazas en ${E(d.row_count)} registros · ${E(d.pages)} páginas.</p><p>${E(d.provenance_label)}</p><div class="buttons">${U.button('open-copy','Consultar copia','grid','primary',`data-id="${E(d.id)}"`)}${U.pdfLink(d)}${U.external(d.source_url,'Página oficial / origen')}</div></article>`).join('')}</div>`+
 U.notice('Cobertura documental limitada','Convocatorias, resultados, incidencias y otras familias documentales no tienen una integración completa. No se reconstruyen a partir de diferencias entre vacantes.','neutral')+
 (m.state.catalog.weekly_schedule?.length?`<details class="panel schedule"><summary>Calendario semanal orientativo de RRHH</summary><p>${E(m.state.catalog.schedule_warning)}</p><table class="table-small"><thead><tr><th>Día</th><th>Hora</th><th>Previsión general</th></tr></thead><tbody>${m.state.catalog.weekly_schedule.map(x=>`<tr><td>${E(x.day)}</td><td>${E(x.time)}</td><td>${E(x.event)}</td></tr>`).join('')}</tbody></table></details>`:'');
}
function profile(m){const functions=BA.unique(allRows(m),'function_code','function'),saved=allRows(m).filter(r=>m.prefs.favorites.includes(r.id));
 return header('Mi seguimiento','Elige tus funciones y guarda lo relevante. Tus preferencias no salen de este navegador.')+historyNotice(m)+
 (m.storageAvailable===false?U.notice('Almacenamiento local no disponible.','Las preferencias solo durarán esta sesión. El navegador no permite conservarlas al cerrar.'):'')+
 `<div class="two-col"><section class="panel"><h2>Funciones que sigo</h2><p>Este selector recoge las funciones de las copias disponibles, no un catálogo completo de todas las listas.</p><div class="search-input mt15">${U.icon('search')}<input class="input" id="profile-search" type="search" placeholder="Busca una función o código…" aria-label="Buscar funciones"></div><div class="profile-functions" id="function-list">${functions.map(([code,name])=>`<label class="function-option" data-function-search="${E(BA.norm(code+' '+name))}"><input type="checkbox" data-profile-function="${E(code)}" ${m.prefs.functions.includes(code)?'checked':''}><span>${E(BA.title(name))}<span class="row-secondary mono" >${E(code)}</span></span></label>`).join('')}</div><p class="profile-count" id="profile-count">${m.prefs.functions.length} funciones seleccionadas</p>${U.button('apply-profile','Ver mis funciones en el buscador','arrow','primary')}</section>
 <div><section class="panel section"><h2>Mi posición en lista</h2><p><strong>No calculable con las fuentes verificadas.</strong> Un número de lista, una posición publicada y una estimación no son lo mismo. Faltan datos comprobables de situaciones activas y reincorporaciones.</p><p>No pedimos DNI, contraseña de Educarm ni certificado digital. Consulta tu situación en el portal oficial.</p><div class="buttons mt17">${U.external(m.state.catalog.sources.find(s=>s.id==='educarm-position')?.url,'Ir a Educarm')}</div></section>
 <section class="panel section"><h2>${saved.length} registros guardados${Number(m.state.history_window?.omitted_documents)>0?' disponibles':''}</h2><p>Los favoritos identifican una fila de una copia concreta. No indican que la plaza siga disponible. No se trasladan automáticamente a otras publicaciones.</p><div class="buttons mt16">${U.button('view-saved','Ver guardadas','bookmark')}${U.button('export-preferences','Exportar preferencias','download')}</div></section>
 <section class="panel"><h2>Avisos y privacidad</h2><p>Los cambios y las publicaciones se consultan dentro de la aplicación. No hay avisos por correo, Telegram ni notificaciones en segundo plano activados.</p><p>Sin cuenta, analítica ni cookies de seguimiento. Tu última revisión personal (no comprobación de fuentes): ${E(BA.date(m.prefs.lastSeen))}.</p><div class="buttons mt16">${U.button('reset-preferences','Borrar datos del navegador','','danger')}</div></section></div></div>`;
}
function sameSourceUrl(a,b){if(!a||!b)return false;try{const left=new URL(a),right=new URL(b);left.hash='';right.hash='';left.searchParams.sort();right.searchParams.sort();return left.href===right.href;}catch{return false;}}
function sources(m){const cat=m.state.catalog,checks=m.state.checks||cat.checks||[],pending=cat.notices.filter(n=>BA.isPendingNotice(n,m.state.documents,m.state.history_documents));
 return header('Fuentes y calidad','Qué está comprobado, qué falta y cómo se ha obtenido cada dato.',refreshButton(m))+historyNotice(m)+
 U.notice('Alcance: vacantes sin cubrir de Secundaria y otros cuerpos',`${canCheck(m)?'El servicio consulta el RSS oficial, el índice de RRHH y los anuncios relevantes dentro de sus límites.':'Esta web consulta la instantánea publicada. El botón solo busca una copia publicada más reciente.'} No incluye la posición personal ni todas las convocatorias, incidencias y resultados.`, 'neutral')+
 `<section class="panel section"><h2>Estado de comprobación</h2>${freshness(m)}<p>${pending.length} publicación(es) sin incorporar. Una comprobación parcial conserva la última copia válida y la fecha del último éxito completo.</p>${m.refreshing?`<p id="refresh-status" role="status">${E(m.refreshMessage||'Buscando publicaciones…')}</p>`:''}</section>`+
 `<section class="section"><div class="section-head"><div><h2>Registro de fuentes</h2><p>Las referencias de la auditoría inicial se distinguen de los intentos recientes.</p></div><span class="pill">${cat.sources.length} referencias</span></div><div class="data-table-wrap">${cat.sources.map(s=>{const check=checks.filter(c=>c.id===s.id||sameSourceUrl(c.url,s.url)).at(-1);return `<article class="source-row"><div><h3>${E(s.name||s.id)}</h3><div class="source-role">${E(s.type||s.role||'Referencia oficial')}</div><p>Nota de auditoría inicial: ${E(s.note||'Sin nota adicional.')}</p>${check?`<p>Intento: ${E(BA.date(check.checked_at,{hour:'2-digit',minute:'2-digit'}))} · ${E(check.status)}${check.error?' · '+E(check.error):''}</p>`:'<p>Sin comprobación reciente registrada para esta referencia.</p>'}</div><div class="source-status ${check?.success?'ok':''}"><span class="dot"></span>${E(check?.status||'Referencia de auditoría')}</div><div class="source-external">${U.external(s.url,'Abrir','')}</div></article>`;}).join('')}</div></section>`+
 (checks.length?`<section class="panel section"><h2>Últimos intentos por recurso</h2><ol class="event-list">${checks.map(c=>`<li class="event"><time>${E(BA.date(c.checked_at,{hour:'2-digit',minute:'2-digit'}))}</time><div><strong>${E(c.id)} · ${E(c.status)}</strong><p>${E(c.error||'')} ${U.external(c.url,'Recurso oficial','')}</p></div></li>`).join('')}</ol></section>`:'')+
 `<section class="section"><div class="section-head"><div><h2>Documentos y procedencia</h2><p>La huella identifica los bytes conservados. No acredita firma ni disponibilidad actual.</p></div></div>${m.state.documents.map(d=>`<div class="panel section"><div class="act-top"><div><h3>${E(BA.date(d.published_at))} · ${E(d.row_count)} registros · ${E(d.places)} plazas</h3><p>${E(d.provenance_label)}</p></div><span class="pill ${d.status==='pending'?'pending':'observed'}">${E({approved:'Incorporada',pending:'En revisión',superseded:'Sustituida'}[d.status]||d.status)}</span></div><div class="hash">SHA-256 · ${E(d.sha256)}</div><p>${E(d.warnings.join(' '))}</p><div class="buttons mt13">${U.pdfLink(d)}${U.external(d.source_url,'Página oficial / origen')}</div></div>`).join('')}</section>`+
 `<section class="panel"><h2>Registro de operaciones</h2><p>Registro técnico de incorporación, no historial administrativo de personas o plazas.</p><ol class="event-list">${m.state.events.slice(0,12).map(e=>`<li class="event"><time>${E(BA.date(e.created_at,{hour:'2-digit',minute:'2-digit'}))}</time><div><strong>${E(e.title)}</strong>${e.details?.reason?`<p>${E(e.details.reason)}</p>`:''}${e.details?.failures?.length?`<p>${E(e.details.failures.join(' · '))}</p>`:''}</div></li>`).join('')||'<li class="event">Sin operaciones registradas.</li>'}</ol></section>`;
}
const views={vacancies,changes,acts,profile,sources};
function shell(m){const nav=[['vacancies','Vacantes','grid'],['changes','Cambios','changes'],['acts','Actos','calendar'],['profile','Mi seguimiento','bookmark'],['sources','Fuentes','shield']];const doc=current(m);
 return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-symbol" aria-hidden="true">b.</span><div><div class="brand-name">Bolsa Abierta</div><div class="brand-subtitle">Información docente abierta</div></div></div><nav class="nav" aria-label="Navegación principal">${nav.map(([id,name,ico])=>`<button class="nav-button ${m.view===id?'active':''}" data-view="${id}" ${m.view===id?'aria-current="page"':''}>${U.icon(ico)}<span>${name}</span></button>`).join('')}</nav><div class="sidebar-bottom"><button class="about" data-action="about">${U.icon('code')}Código abierto</button><p>Prototipo 0.1 · ${canCheck(m)?'servicio de comprobación':'copia publicada'}<br>Sin cuenta. Sin rastreo.</p></div></aside><div class="content"><header class="topbar"><div class="breadcrumb"><strong><span class="desktop-only">Región de </span>Murcia</strong><span>/</span><span>Secundaria y otros cuerpos</span></div><div class="top-status"><span class="dot"></span>${canCheck(m)?'Comprobación disponible':'Copia publicada'}</div></header><main id="main" class="main" tabindex="-1">${views[m.view](m)}</main></div></div>`;
}
window.BAV={shell,current,allRows,displayed,results,coverage};
})();
